/** Канонические ключи запросов. Списки — без фильтров (фильтрация на клиенте),
 * чтобы оптимистические обновления надёжно попадали в единый кэш. */
export const qk = {
  me: ["me"] as const,
  users: ["users"] as const,
  cities: ["cities"] as const,
  materials: ["materials"] as const,
  suppliers: ["suppliers"] as const,
  objects: ["objects"] as const,
  stock: ["stock"] as const,
  movements: ["movements"] as const,
  requests: ["requests"] as const,
  invoices: ["invoices"] as const,
  estimates: ["estimates"] as const,
  estimateCompare: (id: number) => ["estimate-compare", id] as const,
  cash: ["cash"] as const,
  txns: ["txns"] as const,
  inventories: ["inventories"] as const,
  dashboard: ["dashboard"] as const,
  objectExpenses: ["object-expenses"] as const,
  cityAnalytics: ["city-analytics"] as const,
  settings: ["settings"] as const,
  debts: ["debts"] as const,
  kpi: ["kpi"] as const,
};
